export const products = [
    {
        name:'Masala,sm',
        comparePrice:0,
        sellPrice:0,
        listPrice:0
    },
    {
        name:'Masala,md',
        comparePrice:0,
        sellPrice:0,
        listPrice:0
    },
    {
        name:'Masala,lg',
        comparePrice:0,
        sellPrice:0,
        listPrice:0
    },
    {
        name:'Cheese,sm',
        comparePrice:0,
        sellPrice:0,
        listPrice:0
    },
    {
        name:'Cheese,md',
        comparePrice:0,
        sellPrice:0,
        listPrice:0
    },
    {
        name:'Cheese,lg',
        comparePrice:0,
        sellPrice:0,
        listPrice:0
    },
    {
        name:'BBQ,sm',
        comparePrice:0,
        sellPrice:0,
        listPrice:0
    },
    {
        name:'BBQ,md',
        comparePrice:0,
        sellPrice:0,
        listPrice:0
    },
    {
        name:'BBQ,lg',
        comparePrice:0,
        sellPrice:0,
        listPrice:0
    },
    {
        name:'BBQ,sm',
        comparePrice:0,
        sellPrice:0,
        listPrice:0
    },
    {
        name:'BBQ,md',
        comparePrice:0,
        sellPrice:0,
        listPrice:0
    },
    {
        name:'BBQ,lg',
        comparePrice:0,
        sellPrice:0,
        listPrice:0
    }
]